Fix permission in first step of installation
MineWeb/MineWebCMS pull request #279
Opened 2021-05-22 14:01 UTC by StanByes

Certaines personnes n'avait pas mis la perm d'écriture sur ce dossier ce qui rendait la première étape de l'installation (compte admin) inutilisable

2021-07-12 07:59 UTC, Eywek requested changes

2021-07-12 07:59 UTC, Eywek commented on app/webroot/verif-install.php
> +$compatible['chmod'] = (is_writable(ROOT . DS . 'app' . DS . 'Config') && is_writable(ROOT . DS . 'app' . DS . 'Plugin') && is_writable(ROOT . DS . 'app' . DS . 'View' . DS . 'Themed') && is_writable
```suggestion
$compatible['chmod'] = (is_writable(ROOT . DS . 'app' . DS . 'Config') && is_writable(ROOT . DS . 'app' . DS . 'Plugin') && is_writable(ROOT . DS . 'app' . DS . 'View' . DS . 'Themed') && is_writable(ROOT . DS . 'config') && is_writable(ROOT . DS . 'app' . DS . 'tmp') && is_writable(ROOT . DS . 'app' . DS . 'webroot' . DS . 'js')) ? true : false;
```

2021-07-12 07:59 UTC, Eywek commented on app/webroot/verif-install.php
> +    if (!is_writable(ROOT . DS . 'app' . DS . 'webroot/js')) {
```suggestion
    if (!is_writable(ROOT . DS . 'app' . DS . 'webroot' . DS . 'js')) {
```

2021-07-12 14:19 UTC, StanByes commented
I made the requested changes ;)

2021-07-15 12:14 UTC, Eywek approved these changes

2021-07-15 12:14 UTC, merged