Change theme load
MineWeb/MineWebCMS pull request #281
Opened 2021-06-19 12:58 UTC by StanByes

J'ai changé le if dans la fontion de chargement des thèmes pour que le thème soit charger en cas d'erreur sur le panel admin ^^

2021-07-12 08:28 UTC, Eywek requested changes

2021-07-12 08:28 UTC, Eywek commented on app/Controller/AppController.php
> +        if (!isset($this->params['prefix']) or $this->params['prefix'] === "admin" and $this->response->statusCode() === 500 or $this->response->statusCode() === 404 or $this->response->statusCode()
```suggestion
        if (!isset($this->params['prefix']) or $this->params['prefix'] !== "admin" or (isset($this->params['prefix']) and $this->params['prefix'] === "admin" and $this->response->statusCode() >= 400))
```

2021-07-12 14:18 UTC, StanByes commented
I made the requested changes ;)

2021-07-15 12:14 UTC, Eywek approved these changes

2021-07-15 12:14 UTC, merged